### ISSUE TITLE
Supporting Markdown tables

### ISSUE THREAD

**Issue by SabrinaJewson** [SabrinaJewson/cmarker.typ#2]
It would be useful to support Markdown tables and have them be converted into [Typst tables](https://typst.app/docs/reference/layout/table/).

**Comment by aadi58002** [comment]
is this issue still being worked on ?

**Comment by SabrinaJewson** [comment]
Well, [pulldown-cmark supports tables natively](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/enum.Tag.html#variant.Table), so it’s just a question of converting `Table` into a Typst function call and each cell into a parameter. You should be able to handle the `Table` event in a new function, which looks for `TableHead` (converting it to `table.header`) and handles the cells appropriately. If there are any unexpected events from the parser, you can just panic, they shouldn’t be happening.
