### ISSUE TITLE
Note on the use of images

### ISSUE THREAD

**Issue by Doublonmousse** [SabrinaJewson/cmarker.typ#5]
This is an unfortunate consequence of how `eval` is used in typst.

When markdown is parsed with the pakage and contains images, the path to find the `eval` is evaluated relative to the package file, NOT the main file.

When this package is used locally, this might not create any problem as the two files `cmarker.typ` and `main.typ` may well be in the same folder.

But for using the package using the package manager, this makes the code fails as the images are searched relative to whichever folder the package is stored. This issue extends to the web app as well.

To circumvent this, you need to defer the eval step and evaluate the converted typst string in the `main.typ` file. 

For example, 
```typ
#import "@preview/cmarker:0.1.0":* 

#let out = (render(show-source: true,read("simple.md")))
#eval(out.text,mode:"markup")
```
Will work for a simple markdown file that loads a single image but only calling the `render` function will not.

**Comment by SabrinaJewson** [comment]
A slightly nicer solution is the following:

```typst
#import "@preview/cmarker:0.1.1"
#cmarker.render(
  read("yourfile.md"),
  scope: (image: (path, alt: none) => image(path, alt: alt))
)
```

I’ve added a note about this to the README now, so I think it’s fine to close.

**Comment by yao-yun** [comment]
@SabrinaJewson The current solution seems to fail in the following case, and a workaround is possible as is shown. Note that the shown path handling is a quick and dirty demo, and should be handled with more care...  

The directory structure: 
```
.
├── fail.typ
├── nestfolder
│   ├── assets
│   │   └── cmarker.png
│   └── somefile.md
└── test.typ

3 directories, 4 files
```

fail.typ:
```typst
#import "@preview/cmarker:0.1.3"

#let mdfile_dir = "nestfolder/somefile.md"

// This fails

#cmarker.render(
  read(mdfile_dir),
  scope: ( 
    image: (path, alt: none) => image(path, alt: alt)
    )
)
```

test.typ:
```typst
#import "@preview/cmarker:0.1.3"

#let mdfile_dir = "nestfolder/somefile.md"

#let get_work_dir(dir: "") = {
  let work_dir = dir.split("/") // this is hacky, just for quick demo 
  let filename = work_dir.pop()
  work_dir.join("/")
}

// This works!

#let markdown_file(dir, ..args) = {
  cmarker.render(
    read(dir),
    ..args,
    scope: (
      image: (path, alt: none) => {
        let realpath = get_work_dir(dir: dir) + "/" + path
        image(realpath, alt: alt)
        }
      )
  )
}

= MD file source
#box(stroke: 1pt, inset: 5pt, width: 100%,
  raw(read(mdfile_dir))
)

= Rendered markdown 
#box(stroke: 1pt, inset: 5pt, width: 100%,
  markdown_file(mdfile_dir)
)
```

Rendered test.typ:

![Image](https://github.com/user-attachments/assets/9ed0d775-f6bb-47f4-83ef-7d0e505e01ea)

**Comment by SabrinaJewson** [comment]
This seems like expected behaviour – paths resolve relative to where the `image` function is written. I suppose I could add a `relative_to` path to `cmarker` but you seem to have a good workaround.

I guess I’d accept a PR to document this in the README, but I’m mostly waiting for Typst to have native path types to get rid of this issue for good.
